### PR TITLE
Refactor tests and move test scripts into the build directory

### PR DESCRIPTION
**Pull request by cmickeyb**
Several changes... first, moved the test-request and test-contract
scripts out of eservice and into the python directory tree in
pdo/test. These are then installed as pdo-test-request and
pdo-test-contract.

Moved all of the scripts for test-contract out of the eservice tree and
put them into a directory in the build tree.

Added several new tests and restructured the existing ones. Two main
changes. First, added invocation of unit tests for the main packages
that support them (common, python, eservice, and contract). The
enclave-only test-secrets and test-requests are invoked as unit tests
for eservice. Second, changed the enclave configuration so that each
eservice used in the test will use its own data file. Added a "random"
enclave switch to the client update script to randomly pick an
enclave. All this makes it possible to test multiple independent
eservices and to ensure that the client is moving state blocks between
them correctly.

Signed-off-by: Mic Bowman <mic.bowman@intel.com>

### CODE REVIEW

**Comment by g2flyer** [comment]
> run-test fails as common does not have a test make target (but tests are anyway automatically called earlier as part of "normal" make build). Once i comment that out it pass the e2e "docker" test.
> 
> would be good to also use constants for numbers like the 50 (which later requires a corresponding 51)? (or alternatively count down rather than up in which case the termination test does not depend on iterations)

turns out, it's the interplay of building for docker which made run-test fail. For docker builds to work i cannot run any sgx code during a build as it invariably lacks access to SGX HW.  Hence i've added a flag which prevents running tests when build is inside docker. A workaround for problem would be following patch:

```patch
intel@sgx2:~/src/PoET-et-al/pdo/src/private-data-objects.git$ git diff HEAD^
diff --git a/build/__tools__/build.sh b/build/__tools__/build.sh
index de8d922..2e499ec 100755
--- a/build/__tools__/build.sh
+++ b/build/__tools__/build.sh
@@ -70,7 +70,7 @@ CMAKE_ARGS=
 # allow opting out of running tests, primarily so we can skip
 # sgx hw-mode based tests which fail in docker test
 if [ ! -z "${NO_SGX_RUN_DURING_BUILD}" ]; then
-    CMAKE_ARGS+=" -D DISABLE_TESTS=true"
+    CMAKE_ARGS+=" -D DISABLE_RUNNING_TESTS=true"
 fi

 # -----------------------------------------------------------------
diff --git a/build/__tools__/run-tests.sh b/build/__tools__/run-tests.sh
index 7a16094..3eb4d7e 100755
--- a/build/__tools__/run-tests.sh
+++ b/build/__tools__/run-tests.sh
@@ -97,6 +97,7 @@ try make test > /dev/null

 say run unit tests for common library
 cd ${SRCDIR}/common/build
+try cmake -DDISABLE_RUNNING_TESTS=0 .. > /dev/null # make sure we have test targets also when we have built with docker ...
 try make test > /dev/null

 say run unit tests for eservice
diff --git a/common/CMakeVariables.txt b/common/CMakeVariables.txt
index b2c0dbb..8f51bb1 100644
--- a/common/CMakeVariables.txt
+++ b/common/CMakeVariables.txt
@@ -73,7 +73,7 @@ SET(GENERIC_PRIVATE_INCLUDE_DIRS "." ".." "../crypto" "../crypto/verify_ias_repo
 SET(GENERIC_PUBLIC_INCLUDE_DIRS "${SGX_SDK}/include")

 # allow opting out of running tests, primarily so we can skip sgx hw-mode based tests which fail in docker test
-if(NOT DISABLE_TESTS)
+if(NOT DISABLE_RUNNING_TESTS)
     enable_testing()
 endif()

```
(Only problem with patch i see is that you have manually run cmake in common/build with some other options, then they would be blown out.   So a slightly more robust option might try first to run 'make test' and do the cmake (& a second make test) only if make test fails the first time ...

**Comment by bvavala** [comment]
@g2flyer, but like this you "rebuild" something in run-tests.
How about another environment variable (say PDO_ON_DOCKER) which, when it is set, does not run the tests in run-tests and/or skips building/running the tests in the cmake?

**Comment by g2flyer** [comment]
> @g2flyer, but like this you "rebuild" something in run-tests.
> How about another environment variable (say PDO_ON_DOCKER) which, when it is set, does not run the tests in run-tests and/or skips building/running the tests in the cmake?
> 
> Lastly, I suggest any patch to be a separate PR.

Note the tests were always built, regardless of docker or not. the only thing which was missing was that there was a test target which actually _run_ the tests. The cmake in thepatch above doesn't rebuild if you have built before but just adds the test target.   What of course would have been nice if cmake would have added a build-all-but-don't-run-test target in the makefile but nonesuch seems to exist when enable_tests is added to cmakefiles (if you know otherwise, i'm all ear).   Note that when _running_ docker (rather than building) then SGX HW works and run-tests is run at run, not build time. So i wouldn't want to omit tests as it would kindof defeat the purpose of 'make -C docker test'.   Besides the caveat (plus a potential workaround) i mentioned below my proposed patch, i think my patch does get the best of "both world". (I have tested it only with docker but i don't see any issue why it wouldn't work outside of docker)

**Comment by bvavala** [comment]
@g2flyer, if you want to build without running the tests, while being able to run them later with 'make test', you just have to delete 3 chars as follows:
in common/tests/CMakeLists.txt, remove 'ALL' at line 95
-ADD_CUSTOM_TARGET(${TEST_TARGET} **ALL** COMMAND ctest --output-on-failure)
+ADD_CUSTOM_TARGET(${TEST_TARGET} COMMAND ctest --output-on-failure)

**Comment by cmickeyb** [comment]
> in common/tests/CMakeLists.txt, remove 'ALL' at line 95
> -ADD_CUSTOM_TARGET(${TEST_TARGET} **ALL** COMMAND ctest --output-on-failure)
> +ADD_CUSTOM_TARGET(${TEST_TARGET} COMMAND ctest --output-on-failure)

I made this change.

**Comment by g2flyer** [comment]
My patch wouldn't have rebuild anything. That said, Bruno's proposal is clearly better. As-is, it doesn't solve the problem, though. It also needs below patch to work with docker (the patch also addresses my other comment). 

```patch
diff --git a/build/__tools__/build.sh b/build/__tools__/build.sh
index de8d922..73f4000 100755
--- a/build/__tools__/build.sh
+++ b/build/__tools__/build.sh
@@ -67,11 +67,6 @@ if [ "$NUM_CORES " == " " ]; then
 fi

 CMAKE_ARGS=
-# allow opting out of running tests, primarily so we can skip
-# sgx hw-mode based tests which fail in docker test
-if [ ! -z "${NO_SGX_RUN_DURING_BUILD}" ]; then
-    CMAKE_ARGS+=" -D DISABLE_TESTS=true"
-fi

 # -----------------------------------------------------------------
 # BUILD
diff --git a/build/__tools__/run-tests.sh b/build/__tools__/run-tests.sh
index 7a16094..85e98cf 100755
--- a/build/__tools__/run-tests.sh
+++ b/build/__tools__/run-tests.sh
@@ -186,11 +186,12 @@ try pdo-create --config ${CONFIG_FILE} --ledger ${PDO_LEDGER_URL} \
     --identity user1 --save-file ${SAVE_FILE} \
     --contract mock-contract --source _mock-contract.scm

-# this will invoke the increment operation 50 times; the objective
+# this will invoke the increment operation n times; the objective
 # of this test is to ensure that the client touches multiple, independent
 # enclave services and pushes missing state correctly
-say increment the value with a simple expression
-for v in $(seq 1 50) ; do
+declare -i n=50
+say increment the value with a simple expression ${n} times
+for v in $(seq 1 ${n}) ; do
     value=$(pdo-update --config ${CONFIG_FILE} --ledger ${PDO_LEDGER_URL} \
                        --enclave random \
                        --logfile __screen__ --loglevel warn \
@@ -207,7 +208,7 @@ value=$(pdo-update --config ${CONFIG_FILE} --ledger ${PDO_LEDGER_URL} \
                    --logfile __screen__ --loglevel warn \
                    --identity user1 --save-file ${SAVE_FILE} \
                    "(list 'inc-value)")
-if [ $value != "51" ]; then
+if [ $value != $(($n+1)) ]; then
     die contract has the wrong value
 fi

@@ -217,7 +218,7 @@ value=$(pdo-update --config ${CONFIG_FILE} --ledger ${PDO_LEDGER_URL} \
                    --logfile __screen__ --loglevel warn \
                    --identity user1 --save-file ${SAVE_FILE} \
                    "'(get-value)")
-if [ $value != "51" ]; then
+if [ $value != $((51)) ]; then
     die contract has the wrong value
 fi

diff --git a/common/CMakeVariables.txt b/common/CMakeVariables.txt
index b2c0dbb..fff53ff 100644
--- a/common/CMakeVariables.txt
+++ b/common/CMakeVariables.txt
@@ -72,10 +72,7 @@ SET(SGX_ENCLAVE_INCLUDE "${SGX_SDK}/include"
 SET(GENERIC_PRIVATE_INCLUDE_DIRS "." ".." "../crypto" "../crypto/verify_ias_report" "../packages/base64" "../state")
 SET(GENERIC_PUBLIC_INCLUDE_DIRS "${SGX_SDK}/include")

-# allow opting out of running tests, primarily so we can skip sgx hw-mode based tests which fail in docker test
-if(NOT DISABLE_TESTS)
-    enable_testing()
-endif()
+enable_testing()

 ################################################################################
 # Functions
```

**Comment by bvavala** [comment]
The patch looks fine: it removes the dependencies on  NO_SGX_RUN_DURING_BUILD and DISABLE_TESTS

**Comment by cmickeyb** [comment]
changes made to remove the tests. not including the changes to run-test. the generalization is not necessary for the test.

**Pull request merged**
