### PR TITLE
removed dependencies on key_exchange

### PR DESCRIPTION
**Pull request by bvavala**

### CODE REVIEW

**Comment by bvavala** [comment]
Byron, 
can you confirm that the 0b5d27a commit is redundant? (I think it was merged in #12)

**Comment by byron-marohn** [comment]
Yes, that commit is already merged. What is tripping us up here in multiple places is working with forked copies of the repository which aren't automatically updated when something is merged here. 

You basically need to update your fork with the latest changes from the master repository. You can do something like this: 

- Add the "official" repository as a remote for your fork, which you can fetch from. You may have to use an https URL instead if you aren't pushing/pulling via git protocol. 
```git remote add official git@github.com:hyperledger-labs/private-data-objects.git```

- Fetch that remote
```git fetch official```

- Update your master branch to point to the latest official master commit. Note that because of the way the permissions are set up for the "official" repo, it's impossible to accidentally to push to it's master branch (a good thing). This will push to the master branch for your fork. 
```git checkout master
git merge official/master
git push origin master```

- Now you can rebase your branch on master, and that commit should disappear when Git automatically detects that it already exists: 
```git checkout bruno.may21.remove_keyexchange_dependency
git rebase official/master
```
- Finally, push that rebased branch back here which will update the pull request
```
git push origin bruno.may21.remove_keyexchange_dependency --force
```

**Comment by bvavala** [comment]
Nice HowTo! Maybe we could put that in the repo's wiki.

I will remove that commit.

**Comment by byron-marohn** [comment]
Passes tests, looks good.

**Pull request merged**
