### PR TITLE
Fix #173 ensuring that there is one secret from each provisioning service

### LINKED ISSUE #173: Ensure that only one secret comes from each registered provisioning service
A provisioning service may generate multiple secrets for a given PSPK. While this is not correct behavior it shouldn't represent a security problem. 

Check for duplicate PSPK's in the contract enclave to catch this situation.

### PR DESCRIPTION
**Pull request by cmickeyb**
Fix #173 

Signed-off-by: Mic Bowman <mic.bowman@intel.com>

### CODE REVIEW

**Comment by g2flyer** [comment]
While checking for duplicate keys from same provisioining service seem worthwhile (and functionally also seems to work), i don't think it will solve the issue that a malicious provisioning service in collusion with the contract owner can pretend to provision multiple enclaves yet in fact only correctly provision a subset. They can achieve the same thing also by just having a different shares?  In fact, i think the duplicate key could be detected right away on the ledger as the enclave provisioning transaction does seem to bind to the list of provisioning services (at least according to the paper :-) whereas different key shares would not be immediately visible?

If we care to prevent such DoS early (and not only after somebody tries to issue a transaction), then  i think the way to do it would be to use the shared secret not right a way as contract encryption key but as a master-key from which we derive a contract encryption key as well, separatedly, a PK key pair for which the registration transaction would then also explicitly bind to the PK.  (This PK of course could also be then right away to the pool encryption key if we would move to pools?)

**Comment by cmickeyb** [comment]
@g2flyer there is already an issue that requires changes to the Sawtooth TP to address the concern you raised. See #163.

**Comment by g2flyer** [comment]
> @g2flyer there is already an issue that requires changes to the Sawtooth TP to address the concern you raised. See #163.

But not sure what (security) issue is this then to address? As mentioned above, a malicious PS can even do on its own a DoS by providing different shares for different enclaves which are not getting detected until  somebody actually tries to use an enclave?  Note i'm not fundamentally opposed to this test but if we are concerned about early detection of DoS then this PR doesn't solve the issue? (#163 is a different security issue, it's about subverting risk management rather than DoS as here)

**Comment by cmickeyb** [comment]
I have no idea what you're talking about. Lets take it offline.

**Pull request merged**
