### PR TITLE
in-enclave attestation verification (user installs IAS CA certificate)

### PR DESCRIPTION
**Pull request by bvavala**
Signed-off-by: Bruno Vavala <bruno.vavala@intel.com>

### CODE REVIEW

**Comment by bvavala** [comment]
change made

**Comment by byron-marohn** [comment]
Give me a bit to test this before we merge it - I'm seeing a build failure on my system and I'm trying to determine whether it's my system or not.

**Comment by bvavala** [comment]
I have applied those changes.
We need to integrate in the build a check for unsafe functions.

**Comment by aaadesok** [comment]
I am seeing a build failure also. I will discuss with Byron, maybe we have the same issues.

**Comment by byron-marohn** [comment]
Looks good to me - tests in SIM mode still work, and no more banned functions. Merging

**Pull request merged**
