### PR TITLE
Fix of chicken'n'egg script problem, consistency related renaming and some restructure for docker

### PR DESCRIPTION
**Pull request by g2flyer**
* resolve chicken'egg of dummy keys for sgx
* rename key-related variables for more clarity and correct some of the docu
* separate key-directories for sgx-related keys and ledger-related keys
* env var script which is also eval-able and provides variable docu
* some docker-compose related keep/ignores

Signed-off-by: Michael Steiner <michael.steiner@intel.com>

### CODE REVIEW

**Comment by g2flyer** [comment]
PS: above works in simulation mode including run-tests and make test in contracts/auctions and contracts/integer-key.  There is a small bug though in that the files formerly named placebo are not properly renamed with the new naming convention.  This didn't cause any problems when building in SIM but will make verify.sh fail when in HW mode.

I have the fix of that in my docker/docker-compose branch (docker-compose in https://github.com:g2flyer/private-data-objects.git) which is ready for PR as soon as this one is merged into master. 

PS: In that branch i also have a reliable (via docker build as well as from-scratch-with-ubuntu-server-18.04) SW configuration (sdk, sgxssl, openssl, ...) which passes all tests for simulator mode and in sgx mode it fails in docker with the invalid signature which seems a docker issue, unlikely an issue with above config.

**Comment by cmickeyb** [comment]
I'm going to make a couple changes. The PEM file in the Makefile should be conditional on the environment variable. And, the default for the ias key should be consistent and in the /opt/pdo/keys/ directory tree.

**Comment by g2flyer** [comment]
> I'm going to make a couple changes. The PEM file in the Makefile should be conditional on the environment variable. And, the default for the ias key should be consistent and in the /opt/pdo/keys/ directory tree.

Hmm, regarding PEM key the ENCLAVE_CODE_SIGN_KEY was on purpose the "fake" key and i'm not sure why you want that at a different place. My take is the only place to redefine PDO_ENCLAVE_CODE_SIGN_PEM is iff you have an existing (potentially "real") signing key.  So i didn't see a need to use the makefile to generate the key at a non-standard place (in particular for simulation mode).  But if you prefer i can make  ENCLAVE_CODE_SIGN_KEY's value conditional on non-existance of PDO_ENCLAVE_CODE_SIGN_PEM.  However, as mentioned above i'd perfer if we could defer that to a subsequent PR ...

Regarding ias-key, why would you want to install simulation keys in /opt/pdo/keys? (besides, using a def in /opt/pdo/keys was the original source of the chicken'n'egg problem?)

**Comment by cmickeyb** [comment]
Going to merge this one & push my changes separately. Moving *ALL* defaults into common config. Requiring that they all be set in expand config and the Makefile. 

And some streamlining the Makefile.

**Pull request merged**
