### PR TITLE
Initial Ethereum implementation

### PR DESCRIPTION
**Pull request by gcamata**
Signed-off-by: Graziella <graziella.camata@intel.com>

### CODE REVIEW

**Comment by byron-marohn** [comment]
Squashed and rebased everything into one commit that contains just the relevant changes - will review and provide feedback shortly.

**Comment by byron-marohn** [comment]
This looks pretty good - one question: 

You use the terms "contract" and "enclave" a lot in here. I know that's what PDO is based around - but does this actually interact with an SGX enclave or "contract" in any way? Or is it just the infrastructure that would be needed for someone else to hook up "enclave" to actually call methods of an actual SGX enclave? 

Maybe I'm missing something obvious... 

Looking forward to the documentation in a subsequent pull request

**Comment by gcamata** [comment]
The solidity file just holds a “registry” of the available enclaves and contracts— currently there’s no interaction with an actual SGX enclave. It basically acts like a map, linking an enclave’s id with the enclave’s info and a contract’s id with the contract’s info (like which enclaves are permitted to execute it). All this info must be provided by the client when they register an enclave or contract. In that sense it’s just the infrastructure side. As far as I know you can’t make calls to an actual SGX enclave from an Ethereum smart contract.

The only contract interaction is the following: when registering a contract in the contract registry, a call is made to the enclave registry contract to make sure the enclaves that are associated with a contract have already been registered there.
 
As for the python file, it’s just a demo of registering components in deployed contracts. Basically just a couple of set/get calls to those contracts.

**Comment by byron-marohn** [comment]
Thanks! Makes sense to me. Will merge.

**Pull request merged**
