### PR TITLE
Build dependency bug fix

### PR DESCRIPTION
**Pull request by g2flyer**
Discovered testing [PDO contracts PR #32](https://github.com/hyperledger-labs/pdo-contracts/pull/32), see this [comment](https://github.com/hyperledger-labs/pdo-contracts/pull/32#issuecomment-2061716452)

### CODE REVIEW

**Review by cmickeyb — APPROVED** [review]
this looks fine to me. waiting for @bvavala to test.

**Comment by g2flyer** [comment]
> this looks fine to me. waiting for @bvavala to test.

looks fine but isn't ;-) just realized that it currently doesn't work for `sgx_text` ...

**Comment by g2flyer** [comment]
> > this looks fine to me. waiting for @bvavala to test.
> 
> looks fine but isn't ;-) just realized that it currently doesn't work for `sgx_text` ...

Now it does ...

**Review by bvavala — APPROVED** [review]

**Comment by bvavala** [comment]
> > > this looks fine to me. waiting for @bvavala to test.
> > 
> > 
> > looks fine but isn't ;-) just realized that it currently doesn't work for `sgx_text` ...
> 
> Now it does ... (_Note: fix is in fixup comment, so unless you want to do a squash-merge, @bvavala ping me before merging and i do the auto-squash_)

Looks good, do you want to squash the commits?

**Comment by g2flyer** [comment]
> > > > this looks fine to me. waiting for @bvavala to test.
> > > 
> > > 
> > > looks fine but isn't ;-) just realized that it currently doesn't work for `sgx_text` ...
> > 
> > 
> > Now it does ... (_Note: fix is in fixup comment, so unless you want to do a squash-merge, @bvavala ping me before merging and i do the auto-squash_)
> 
> Looks good, do you want to squash the commits?

done

**Pull request merged**
